2025-11-26 22:17:34.929 [Information] /home/mohammed/RiderProjects/Todo-List-AvaloniaUI/TodoListApp/bin/Debug/net9.0/logs/app.log: Tray icon created successfully
2025-11-26 22:17:40.125 [Information] /home/mohammed/RiderProjects/Todo-List-AvaloniaUI/TodoListApp/bin/Debug/net9.0/logs/app.log: Window hidden to system tray
2025-11-26 23:00:22.902 [Information] /home/mohammed/RiderProjects/Todo-List-AvaloniaUI/TodoListApp/bin/Debug/net9.0/logs/app.log: Tray icon created successfully
2025-11-26 23:00:42.068 [Information] /home/mohammed/RiderProjects/Todo-List-AvaloniaUI/TodoListApp/bin/Debug/net9.0/logs/app.log: Window hidden to system tray
2025-11-26 23:00:44.155 [Information] /home/mohammed/RiderProjects/Todo-List-AvaloniaUI/TodoListApp/bin/Debug/net9.0/logs/app.log: Window shown from tray
2025-11-26 23:00:48.104 [Information] /home/mohammed/RiderProjects/Todo-List-AvaloniaUI/TodoListApp/bin/Debug/net9.0/logs/app.log: Window hidden to system tray
2025-11-26 23:03:06.178 [Information] /home/mohammed/RiderProjects/Todo-List-AvaloniaUI/TodoListApp/bin/Debug/net9.0/logs/app.log: Tray icon created successfully
2025-11-26 23:03:33.708 [Information] /home/mohammed/RiderProjects/Todo-List-AvaloniaUI/TodoListApp/bin/Debug/net9.0/logs/app.log: Window hidden to system tray
2025-11-26 23:09:51.930 [Information] /home/mohammed/RiderProjects/Todo-List-AvaloniaUI/TodoListApp/bin/Debug/net9.0/logs/app.log: Tray icon created successfully
2025-11-26 23:10:53.619 [Information] /home/mohammed/RiderProjects/Todo-List-AvaloniaUI/TodoListApp/bin/Debug/net9.0/logs/app.log: Window hidden to system tray
